name: Deploy to Fly.io

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  FLY_APP: bitwarden
  FLY_VOLUME: vaultwarden_data

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Fly.io
        uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          access-token: ${{ secrets.FLY_API_TOKEN }}

      - name: Deploy App
        run: |
          flyctl deploy --remote-only --app $FLY_APP
          flyctl volumes list --app $FLY_APP | grep $FLY_VOLUME || flyctl volumes create $FLY_VOLUME --app $FLY_APP --region hkg --size 1
          
      - name: Configure Secrets
        run: |
          echo "Setting environment variables"
          flyctl secrets set \
            ADMIN_TOKEN=${{ secrets.ADMIN_TOKEN }} \
            SMTP_HOST=${{ secrets.SMTP_HOST }} \
            SMTP_FROM=${{ secrets.SMTP_FROM }} \
            --app $FLY_APP

      - name: Trigger Restart
        run: flyctl apps restart $FLY_APP
